#!/usr/bin/env node
/* ════════════════════════════════════════════════════════════
   encrypt.js — build-time encryption for the monthsary site
   ─────────────────────────────────────────────────────────
   Usage:  node encrypt.js <password>
   Reads:  letter.html   (the plaintext letter)
   Writes: js/encrypted.js (salt + iv + ciphertext, all base64)

   The password is used via PBKDF2 → AES-256-GCM.
   At runtime the browser uses the Web Crypto API to decrypt.
════════════════════════════════════════════════════════════ */
const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const password = process.argv[2];
if (!password) {
  console.error('Usage: node encrypt.js <password>');
  console.error('  e.g. node encrypt.js strawberry');
  process.exit(1);
}

const letterPath = path.join(__dirname, 'letter.html');
if (!fs.existsSync(letterPath)) {
  console.error('✗ letter.html not found — create it first.');
  process.exit(1);
}

const plaintext = fs.readFileSync(letterPath, 'utf8');

// cryptographic parameters
const salt = crypto.randomBytes(16);
const iv = crypto.randomBytes(12);       // 96-bit IV for AES-GCM
const iterations = 100_000;

// derive a 256-bit key from the password (lowercased + trimmed, matching runtime)
const normalisedPw = password.trim().toLowerCase();
const key = crypto.pbkdf2Sync(normalisedPw, salt, iterations, 32, 'sha256');

// encrypt
const cipher = crypto.createCipheriv('aes-256-gcm', key, iv);
const encrypted = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
const tag = cipher.getAuthTag();          // 128-bit auth tag

// write the output
const outPath = path.join(__dirname, 'js', 'encrypted.js');
const output = `// Generated by encrypt.js — do not edit by hand
// Re-run:  node encrypt.js <password>
var ENCRYPTED = {
  salt: '${salt.toString('base64')}',
  iv:   '${iv.toString('base64')}',
  tag:  '${tag.toString('base64')}',
  data: '${encrypted.toString('base64')}',
  iter: ${iterations}
};
`;

fs.writeFileSync(outPath, output, 'utf8');
console.log(`✓ Encrypted ${plaintext.length} bytes → js/encrypted.js`);
console.log(`  salt  ${salt.toString('base64')}`);
console.log(`  iv    ${iv.toString('base64')}`);
console.log(`  iter  ${iterations}`);
